### ISSUE TITLE
OpenSSL removed SHA-0

### ISSUE THREAD

**Issue by Hoikas** [H-uru/dirtsand#111]
OpenSSL has removed support for SHA-0. This causes Types/ShaHash.cpp#L75 to not work properly and break compilation. This functionality is used to create email address style accounts, which has never been particularly emphasized by DS.

See: https://www.openssl.org/blog/blog/2015/07/28/code-cleanup/
"We also removed support for the broken **SHA0** and DSS0, the CBCM mode of DES (invented by IBM and not used anywhere), and the maintenance of our own free lists, OPENSSL_NO_BUF_FREELISTS."

**Comment by zrax** [comment]
Well crap.  I suppose we could throw a warning and reject login if we were built with a newer OpenSSL...  I'd hate to just remove it unless we fix the client too, but that would potentially break compatibility unless we're careful about how we deprecate it.  Since the client uses the same SHA0 code, it will eventually be broken by those with newer OpenSSL libraries as well.

**Comment by Hoikas** [comment]
The good news is that SHA-0 is only used if the username matches a certain format (is an email address), otherwise, SHA-1 is used. Yay for Cyanic redundancy. For Gehn 25 Beta, I replaced the Sha0 function with `DS_PASSERT(0)` because that code path is never used on Gehn :smile:

**Comment by Deledrius** [comment]
:trollface:

**Comment by zrax** [comment]
Resolved by #130.
